spring.application.name=cosmos-management

spring.datasource.url=${DB_URL:jdbc:postgresql://51.68.26.106:5432/cosmos}
spring.datasource.username=${DB_USER:aed}
spring.datasource.password=${DB_PASSWORD:6x[EE4JCaU4C}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update




